### ISSUE TITLE
Problems while installing plugin

### ISSUE THREAD

**Issue by ghost** [pdemarco925/homebridge-doorsensor#4]
Hi!
I installed the plugin and tried to run it with triggerfile option but it doesn't work. Here's the error code:`[2018-5-21 23:07:38] ====================
[2018-5-21 23:07:38] ERROR LOADING PLUGIN homebridge-doorsensor:
[2018-5-21 23:07:38] Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/build/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/build/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/build/Release/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/out/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/out/Release/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/Release/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/build/default/rpio.node
 → /usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/compiled/8.11.1/linux/arm                                                                   /rpio.node
    at bindings (/usr/lib/node_modules/homebridge-doorsensor/node_modules/bindings/binding                                                                   s.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-doorsensor/node_modules/rpio/l                                                                   ib/rpio.js:17:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-doorsensor/index.js:11:12)
[2018-5-21 23:07:38] ====================
`

**Comment by pdemarco925** [comment]
Can you check to see if this file exists on your system? 
/usr/lib/node_modules/homebridge-doorsensor/node_modules/bindings/bindings.js

If not, try installing the bindings npm package manually.
If it does exist, is it readable? It should look like this https://github.com/TooTallNate/node-bindings/blob/master/bindings.js 

I think I've run into this error before where that file somehow either had a bad install, or somehow becomes unreadable with extra escape characters in it.

Let me know if this helps.
